CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    cash_balance DECIMAL(19, 2) NOT NULL CHECK (cash_balance >= 0),
    CONSTRAINT fk_wallets_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE portfolio_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    quantity DECIMAL(28, 8) NOT NULL CHECK (quantity >= 0),
    CONSTRAINT fk_portfolio_assets_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_portfolio_user_symbol UNIQUE (user_id, symbol)
);

CREATE TABLE trade_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type IN ('BUY', 'SELL')),
    symbol VARCHAR(10) NOT NULL,
    quantity DECIMAL(28, 8) NOT NULL CHECK (quantity > 0),
    execution_price DECIMAL(19, 8) NOT NULL CHECK (execution_price > 0),
    total_amount DECIMAL(19, 2) NOT NULL CHECK (total_amount > 0),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_trade_transactions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_trade_user_created_at ON trade_transactions (user_id, created_at DESC);

CREATE TABLE price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL,
    price DECIMAL(19, 8) NOT NULL CHECK (price > 0),
    recorded_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_price_history_symbol_recorded_at ON price_history (symbol, recorded_at DESC);